name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build WeiBainingAI using iPhone simulator 15 Pro Max
    # runs-on: macos-latest
    runs-on: self-hosted
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      

      - name: Install Dependencies
        run: |
          xcodebuild -resolvePackageDependencies
  
      # - name: Build
      #   run: |
      #     xcodebuild build -scheme WeiBainingAI -sdk iphoneos -configuration Debug
   
      - name: Build
        run: xcodebuild -scheme WeiBainingAI -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max' build
